apiVersion: v1
kind: Service
metadata:
  name: ${EKS_APP_USER_NAME}-svc
  namespace: ${EKS_NAMESPACE}
spec:
#  serviceAccountName: $GKE_SERVICE_ACCOUNT
  type: LoadBalancer
  selector:
    app: ${EKS_APP_USER_NAME}
  ports:
  - port: 50443
    targetPort: 50443