apiVersion: v1
kind: Service
metadata:
  name: $GKE_SERVICE-user
  namespace: $GKE_NAMESPACE
spec:
#  serviceAccountName: $GKE_SERVICE_ACCOUNT
  type: LoadBalancer
  selector:
    app: $GKE_APP_USER_NAME
  ports:
  - port: 50443
    targetPort: 50443