apiVersion: v1
kind: Service
metadata:
  name: $GKE_SERVICE-admin
  namespace: $GKE_NAMESPACE
spec:
#  serviceAccountName: $GKE_SERVICE_ACCOUNT
  type: LoadBalancer
  selector:
    app: $GKE_APP_ADMIN_NAME
  ports:
  - port: 30443
    targetPort: 30443