apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-postgres
  namespace: flaskapp1-namespace
  labels:
    app: example-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
