kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: podpvc
  namespace: flaskapp1-namespace 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 30Gi


