# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: postgres-pv-volume
#   namespace: flaskapp1-namespace
#   labels:
#     type: local
#     app: postgres
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 12Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: flaskapp1-namespace
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
