apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc-claim
  namespace: flaskapp1-namespace
  labels:
    app: flaskapi
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
