apiVersion: v1
kind: Service
metadata:
  name: postgres11
  namespace: flaskapp1-namespace
  labels:
    app: flaskapi
spec:
  ports:
    - port: 5432
  type: LoadBalancer
  selector:
    app: flaskapi
