apiVersion: v1
kind: Service
metadata:
  name: example-postgres
  namespace: flaskapp1-namespace
  labels:
    app: example-app
spec:
  ports:
    - port: 5432
  type: LoadBalancer
  selector:
    app: example-app
